### ISSUE TITLE
can't save new set (list)

### ISSUE THREAD

**Issue by MalekBakary** [thomasdilts/churchsongs#37]
PDOException: SQLSTATE[HY000]: General error: 1267 Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8mb3_general_ci,COERCIBLE) for operation '=' in /var/www/html/zamar/vendor/yiisoft/yii2/db/Command.php:1302
Stack trace:
#0 /var/www/html/zamar/vendor/yiisoft/yii2/db/Command.php(1302): PDOStatement->execute()
#1 /var/www/html/zamar/vendor/yiisoft/yii2/db/Command.php(1168): yii\db\Command->internalExecute()
#2 /var/www/html/zamar/vendor/yiisoft/yii2/db/Command.php(436): yii\db\Command->queryInternal()
#3 /var/www/html/zamar/vendor/yiisoft/yii2/db/Query.php(446): yii\db\Command->queryScalar()
#4 /var/www/html/zamar/vendor/yiisoft/yii2/validators/UniqueValidator.php(195): yii\db\Query->exists()
#5 /var/www/html/zamar/vendor/yiisoft/yii2/validators/UniqueValidator.php(153): yii\validators\UniqueValidator->modelExists()
#6 [internal function]: yii\validators\UniqueValidator->yii\validators\{closure}()
#7 /var/www/html/zamar/vendor/yiisoft/yii2/db/Connection.php(1130): call_user_func()
#8 /var/www/html/zamar/vendor/yiisoft/yii2/validators/UniqueValidator.php(154): yii\db\Connection->useMaster()
#9 /var/www/html/zamar/vendor/yiisoft/yii2/validators/Validator.php(260): yii\validators\UniqueValidator->validateAttribute()
#10 /var/www/html/zamar/vendor/yiisoft/yii2/base/Model.php(368): yii\validators\Validator->validateAttributes()
#11 /var/www/html/zamar/vendor/yiisoft/yii2/db/ActiveRecord.php(564): yii\base\Model->validate()
#12 /var/www/html/zamar/vendor/yiisoft/yii2/db/BaseActiveRecord.php(676): yii\db\ActiveRecord->insert()
#13 /var/www/html/zamar/frontend/controllers/ListController.php(253): yii\db\BaseActiveRecord->save()
#14 [internal function]: frontend\controllers\ListController->actionCreate()
#15 /var/www/html/zamar/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#16 /var/www/html/zamar/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#17 /var/www/html/zamar/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#18 /var/www/html/zamar/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction()
#19 /var/www/html/zamar/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest()
#20 /var/www/html/zamar/frontend/web/index.php(18): yii\base\Application->run()
#21 {main}

Next yii\db\Exception: SQLSTATE[HY000]: General error: 1267 Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8mb3_general_ci,COERCIBLE) for operation '='
The SQL being executed was: SELECT EXISTS(SELECT * FROM `user_lists` WHERE `user_lists`.`name`='تجربة 01') in /var/www/html/zamar/vendor/yiisoft/yii2/db/Schema.php:676
Stack trace:
#0 /var/www/html/zamar/vendor/yiisoft/yii2/db/Command.php(1307): yii\db\Schema->convertException()
#1 /var/www/html/zamar/vendor/yiisoft/yii2/db/Command.php(1168): yii\db\Command->internalExecute()
#2 /var/www/html/zamar/vendor/yiisoft/yii2/db/Command.php(436): yii\db\Command->queryInternal()
#3 /var/www/html/zamar/vendor/yiisoft/yii2/db/Query.php(446): yii\db\Command->queryScalar()
#4 /var/www/html/zamar/vendor/yiisoft/yii2/validators/UniqueValidator.php(195): yii\db\Query->exists()
#5 /var/www/html/zamar/vendor/yiisoft/yii2/validators/UniqueValidator.php(153): yii\validators\UniqueValidator->modelExists()
#6 [internal function]: yii\validators\UniqueValidator->yii\validators\{closure}()
#7 /var/www/html/zamar/vendor/yiisoft/yii2/db/Connection.php(1130): call_user_func()
#8 /var/www/html/zamar/vendor/yiisoft/yii2/validators/UniqueValidator.php(154): yii\db\Connection->useMaster()
#9 /var/www/html/zamar/vendor/yiisoft/yii2/validators/Validator.php(260): yii\validators\UniqueValidator->validateAttribute()
#10 /var/www/html/zamar/vendor/yiisoft/yii2/base/Model.php(368): yii\validators\Validator->validateAttributes()
#11 /var/www/html/zamar/vendor/yiisoft/yii2/db/ActiveRecord.php(564): yii\base\Model->validate()
#12 /var/www/html/zamar/vendor/yiisoft/yii2/db/BaseActiveRecord.php(676): yii\db\ActiveRecord->insert()
#13 /var/www/html/zamar/frontend/controllers/ListController.php(253): yii\db\BaseActiveRecord->save()
#14 [internal function]: frontend\controllers\ListController->actionCreate()
#15 /var/www/html/zamar/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#16 /var/www/html/zamar/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#17 /var/www/html/zamar/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#18 /var/www/html/zamar/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction()
#19 /var/www/html/zamar/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest()
#20 /var/www/html/zamar/frontend/web/index.php(18): yii\base\Application->run()
#21 {main}
Additional Information:
Array
(
    [0] => HY000
    [1] => 1267
    [2] => Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8mb3_general_ci,COERCIBLE) for operation '='
)

**Comment by MalekBakary** [comment]
It seems like I can save the set name in English but not in Arabic
